# Generated by Django 3.1.1 on 2020-09-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profiles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='DD/MM/AAAA', max_length=100)),
                ('nascimento', models.CharField(help_text='DD/MM/AAAA', max_length=10)),
                ('email', models.EmailField(max_length=254)),
                ('telefone', models.CharField(help_text='(DDD) 9XXXX-XXXX', max_length=16)),
                ('cep', models.CharField(help_text='XXXXX-XXX', max_length=16)),
                ('JAVA', models.BooleanField(default=False, verbose_name='Java')),
                ('NODE', models.BooleanField(default=False, verbose_name='Node.js')),
                ('CPP', models.BooleanField(default=False, verbose_name='C++')),
                ('PHP', models.BooleanField(default=False, verbose_name='PHP')),
                ('PYTHON', models.BooleanField(default=False, verbose_name='Python')),
                ('GO', models.BooleanField(default=False, verbose_name='Go')),
                ('ADVPL', models.BooleanField(default=False, verbose_name='ADVPL')),
                ('ANGULAR', models.BooleanField(default=False, verbose_name='Angular')),
                ('ELECTRON', models.BooleanField(default=False, verbose_name='Electron')),
                ('REACT', models.BooleanField(default=False, verbose_name='React')),
                ('NATIVE', models.BooleanField(default=False, verbose_name='React Native')),
                ('MONGO', models.BooleanField(default=False, verbose_name='MongoDB')),
                ('SQL', models.BooleanField(default=False, verbose_name='MySQL')),
                ('SQLSERVER', models.BooleanField(default=False, verbose_name='SQLServer')),
                ('POSTGRES', models.BooleanField(default=False, verbose_name='Postgres')),
                ('BACKEND', models.BooleanField(default=False, verbose_name='Backend')),
                ('FRONTEND', models.BooleanField(default=False, verbose_name='Front-End')),
            ],
        ),
    ]
