# Generated by Django 3.1.1 on 2020-09-30 03:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20200930_0353'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profiles',
            old_name='Formacoes',
            new_name='formations',
        ),
    ]
