# Generated by Django 3.1.1 on 2020-09-30 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_auto_20200930_0354'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='cod',
            field=models.IntegerField(default=1),
        ),
    ]
