# Generated by Django 3.1.1 on 2020-09-30 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profiles_cod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='cod',
            field=models.IntegerField(db_index=True, default=1),
        ),
    ]
