# Generated by Django 3.1.1 on 2020-09-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_auto_20200930_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='cod',
            field=models.IntegerField(db_index=True),
        ),
    ]
