# Generated by Django 3.1.1 on 2020-09-30 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_auto_20200930_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='cod',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
