# Generated by Django 3.1.1 on 2020-10-01 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_auto_20200930_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profiles',
            name='email',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
